#test
knife4j:
  enable: true
spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123321
  data:
    mongodb:
      uri: mongodb://xxxx:xxxx@127.0.01:3717/xxx
      auto-index-creation: true
#config logback filepath
logback:
  path: /app/xxx/logs/center
